namespace: default
resources:
  - nginx.yaml
  - mysql.yaml
  - backend.yaml
  #- redis.yaml
  #- secret.yaml
  - frontend.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - configs/init.sql
      

patches:
- target:
    kind: Deployment
    name: frontend
  patch: |-
    spec:
      template:
        spec:
          containers:
          - name: frontend
            volumeMounts:
            - name: shared-data
              mountPath: /image

- target:
    kind: Deployment
    name: backend
  patch: |-
    spec:
      template:
        spec:
          containers:
          - name: backend
            volumeMounts:
            - name: shared-data
              mountPath: /image